
//-----------------------------------------------------------------------
// <copyright file=" constphoneprefix.cs" company="xxxx Enterprises">
// * Copyright (C) 2019 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: constphoneprefix.cs
// * history : Created by T4 07/27/2019 16:44:41
// </copyright>
//-----------------------------------------------------------------------
using Repository.Entity.BaseEntities;
using System;
using System.ComponentModel.DataAnnotations;

namespace Repository.Entity
{
    /// <summary>
    /// constphoneprefix Entity Model
    /// </summary>   
    public class recordType: tianleClassEntityBase
    {
   
        /// <summary>
        /// ¿‡–Õ√˚≥∆
        /// </summary>
        public string name { get; set; }
    }
}
